### ISSUE TITLE
Top Negative and Top Positive Tweeter of the day

### ISSUE THREAD

**Issue by nick3703** [dusty-turner/USMAPAO#3]
Let's add a 'top negative' and 'top positive' tweeter and some of the key words that caused us to classify that person as negative or positive.  By top, I mean a person who is influential and is talking negative/positively about USMA

**Comment by dusty-turner** [comment]
I think I've addressed this - in a little bit different way.  It allows the user to select positive or negative -- and also sort based off the most followers or most favorited.  Of course, I can adjust if we don't like the functionality.

**Comment by nick3703** [comment]
I think for the dictionary we are using this is good now.  I do think we need to adjust, perhaps, the dictionary, but that will take PAO help.  I'm going to close this for now, but I will think about it a bit more.  Thanks!
